/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import clases.Conexion;

/**
 *
 * @author Flia. Durán Cuello
 */
public class Login extends javax.swing.JFrame {

    public static String nombre = "";
    public static String ID = "";
    String password = "";
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(300, 450);
        setResizable(false);
        setTitle("Login");
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        
        ImageIcon icon_id = new ImageIcon("src/images/19339625881548233621-256.png");
        Icon ico_id = new ImageIcon(icon_id.getImage().getScaledInstance(jLabel_ico_id.getWidth(), jLabel_ico_id.getHeight(), Image.SCALE_DEFAULT));
        jLabel_ico_id.setIcon(ico_id);
        this.repaint();

        ImageIcon icon_pass = new ImageIcon("src/images/1923.png");
        Icon ico_pass = new ImageIcon(icon_pass.getImage().getScaledInstance(jLabel_ico_pass.getWidth(), jLabel_ico_pass.getHeight(), Image.SCALE_DEFAULT));
        jLabel_ico_pass.setIcon(ico_pass);
        this.repaint();
    }

    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/codinglove.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ico_id = new javax.swing.JLabel();
        txt_id_alumno = new javax.swing.JTextField();
        jLabel_ico_pass = new javax.swing.JLabel();
        txt_password_alumno = new javax.swing.JPasswordField();
        jLabel_1 = new javax.swing.JLabel();
        jLabel_footer = new javax.swing.JLabel();
        jButton_Acceder = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_ico_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 192, 18, 18));

        txt_id_alumno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_id_alumno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id_alumno.setToolTipText("Introduce tu ID de estudiante.");
        txt_id_alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_id_alumno.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        txt_id_alumno.setSelectionColor(new java.awt.Color(0, 0, 153));
        getContentPane().add(txt_id_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 190, 170, 25));
        txt_id_alumno.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jLabel_ico_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 230, 23, 23));

        txt_password_alumno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_password_alumno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password_alumno.setToolTipText("Introduce tu clave.");
        txt_password_alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_password_alumno.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        txt_password_alumno.setSelectionColor(new java.awt.Color(0, 0, 153));
        getContentPane().add(txt_password_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 230, 170, 25));
        txt_password_alumno.getAccessibleContext().setAccessibleName("");

        jLabel_1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_1.setText("INGRESAR:");
        getContentPane().add(jLabel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 50));

        jLabel_footer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_footer.setText("Creado por Oscar Durán ®");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 390, -1, -1));

        jButton_Acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ingresar.png"))); // NOI18N
        jButton_Acceder.setToolTipText("Iniciar sesión");
        jButton_Acceder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Acceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Acceder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ingresar_verde.png"))); // NOI18N
        jButton_Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AccederActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 60, 60));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AccederActionPerformed

        ID = txt_id_alumno.getText().trim();
        password = txt_password_alumno.getText().trim();

        if (!ID.equals("") || !password.equals("")) {
            try {
                try (Connection cn = Conexion.conectar()) {
                    try (PreparedStatement pst = cn.prepareStatement(
                            "select nombre_alumno from usuarios where id_alumno = '" + ID
                                    + "' and password_alumno = '" + password + "'")) {
                        ResultSet rs = pst.executeQuery();
                        if (rs.next()) {
                            
                            nombre = rs.getString("nombre_alumno");
                            
                            JOptionPane.showMessageDialog(null, "Bienvenido " + nombre);
                            dispose();
                            new Menu().setVisible(true);
                            
                        } else {
                            
                            JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos.");
                            txt_id_alumno.setText("");
                            txt_password_alumno.setText("");
                        }
                        pst.close();
                    }
                    cn.close();
                }
                
            } catch (SQLException e) {

                System.err.println("Error en el botón Acceder de Login. " + e);
                JOptionPane.showMessageDialog(null, "Error en la conexión. Contacte con el administrador.");
            }
        } else {

            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
        }

    }//GEN-LAST:event_jButton_AccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Acceder;
    private javax.swing.JLabel jLabel_1;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_ico_id;
    private javax.swing.JLabel jLabel_ico_pass;
    private javax.swing.JTextField txt_id_alumno;
    private javax.swing.JPasswordField txt_password_alumno;
    // End of variables declaration//GEN-END:variables
}
