/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author Flia. Durán Cuello
 */
public class Menu extends javax.swing.JFrame {
    
    String nombre = Login.nombre;
    public static String carrera = "";
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setSize(550, 300);
        setResizable(false);
        setTitle("Menú - Sesión de " + nombre);
        setLocationRelativeTo(null);
        TransparenciaButton();
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select carrera_alumno from usuarios where id_alumno = '" + Login.ID + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                carrera = rs.getString("carrera_alumno");
                jLabel_Titulo.setText(nombre + " - " + carrera);
            }
        } catch (SQLException e) {
            System.err.println("Error en consultar carrera del alumno. " + e);
            JOptionPane.showMessageDialog(null, "Error en la conexión local. Contacte al administrador.");
        }
    }
    
    /*
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/codinglove.png"));
        return retValue;
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jButton_Pensum = new javax.swing.JButton();
        jButton_Calendario = new javax.swing.JButton();
        jButton_Calificaciones = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_Pensum = new javax.swing.JLabel();
        jLabel_Calendario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Titulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Titulo.setText("jLabel1");
        jLabel_Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton_Pensum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/libros-icono.png"))); // NOI18N
        jButton_Pensum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PensumActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Pensum, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 80, 100, 100));

        jButton_Calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario02.png"))); // NOI18N
        jButton_Calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalendarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 80, 100, 100));

        jButton_Calificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grades_icon.png"))); // NOI18N
        jButton_Calificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalificacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Calificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 80, 100, 100));

        jLabel_footer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_footer.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_footer.setText("Creado por Oscar Durán ®");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel_Pensum.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Pensum.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Pensum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Pensum.setText("Pensum");
        getContentPane().add(jLabel_Pensum, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 180, -1, -1));

        jLabel_Calendario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Calendario.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Calendario.setText("Calendario");
        getContentPane().add(jLabel_Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 180, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Calificaciones");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void TransparenciaButton(){
        jButton_Pensum.setOpaque(false);
        jButton_Pensum.setContentAreaFilled(false);
        jButton_Pensum.setBorderPainted(false);
        jButton_Calendario.setOpaque(false);
        jButton_Calendario.setContentAreaFilled(false);
        jButton_Calendario.setBorderPainted(false);
        jButton_Calificaciones.setOpaque(false);
        jButton_Calificaciones.setContentAreaFilled(false);
        jButton_Calificaciones.setBorderPainted(false);
    }
    
    private void jButton_CalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CalendarioActionPerformed

    private void jButton_PensumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PensumActionPerformed
        new Pensum().setVisible(true);
    }//GEN-LAST:event_jButton_PensumActionPerformed

    private void jButton_CalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalificacionesActionPerformed
        new Calificaciones().setVisible(true);
    }//GEN-LAST:event_jButton_CalificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Calendario;
    private javax.swing.JButton jButton_Calificaciones;
    private javax.swing.JButton jButton_Pensum;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Calendario;
    private javax.swing.JLabel jLabel_Pensum;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    // End of variables declaration//GEN-END:variables
}
